### ISSUE TITLE
Challenge/Response error with SniTun server

### ISSUE THREAD

**Issue by sym0nd0** [NabuCasa/snitun#118]
Logs in HA have been displaying the following errors, following each restart of my instance.

```Logger: snitun.client.client_peer
Source: /usr/local/lib/python3.9/site-packages/snitun/client/client_peer.py:84
First occurred: 3:44:31 am (1 occurrences)
Last logged: 3:44:31 am

Challenge/Response error with SniTun server
```
```Logger: hass_nabucasa.remote
Source: /usr/local/lib/python3.9/site-packages/hass_nabucasa/remote.py:323
First occurred: 3:44:31 am (1 occurrences)
Last logged: 3:44:31 am

Connection problem to snitun server
```
There is a long running [issue open](https://github.com/home-assistant/core/issues/41420#issuecomment-908666252) on Core's git. Error's persist through HA updates, from at least 0.116.0. Opening fresh issue here for visibility, by specific team.

Nabu Casa Remote Control connects and works as expected and the Cloud Status shows as Connected in HA.

## System Health

version | core-2021.8.8
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.6
os_name | Linux
os_version | 5.10.17-v8
arch | aarch64
timezone | Europe/London

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 5000
Installed Version | 1.15.1
Stage | running
Available Repositories | 938
Installed Repositories | 13

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 10 September 2021, 1:00 am
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.2
-- | --
update_channel | stable
supervisor_version | supervisor-2021.06.8
docker_version | 20.10.6
disk_total | 219.4 GB
disk_used | 10.3 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.0.1), MariaDB (2.4.0), File editor (5.3.3), Duck DNS (1.13.0), Terminal & SSH (9.1.3), Node-RED (10.0.0), TasmoAdmin (0.15.0), Assistant Relay (0.7.4), Home Assistant Google Drive Backup (0.104.3), TasmoBackup (1.04.23), Zigbee2mqtt (1.21.0-4), NGINX Home Assistant SSL proxy (3.0.2), Grocy (0.15.0), AppDaemon 4 (0.7.0), Samba share (9.5.1)

</details>

<details><summary>Lovelace</summary>

dashboards | 3
-- | --
resources | 6
views | 2
mode | storage

</details>

**Comment by pergolafabio** [comment]
since 2 days, upon  restart  i always see this error below, so it takes a while now before i can connect to my instance

`2021-09-02 11:05:35 ERROR (MainThread) [hass_nabucasa.remote] Timeout connecting to snitun server`

**Comment by Giel538** [comment]
[code]
Connection problem to snitun server
16:29:13 – (FOUT) /usr/local/lib/python3.9/site-packages/hass_nabucasa/remote.py
Challenge/Response error with SniTun server
16:29:13 – (FOUT) /usr/local/lib/python3.9/site-packages/snitun/client/client_peer.py
[/code]

I got this error since the update to 2021.9.x Never seen it before. Nabu casa still works fine.

**Comment by JoJa1101** [comment]
Same here, also happens in 2021.11.X

**Comment by WRLPDZ** [comment]
Same here. Problem still occure.

Logger: snitun.client.client_peer
Source: /usr/local/lib/python3.9/site-packages/snitun/client/client_peer.py:104
First occurred: 10 June 2022, 22:34:18 (3 occurrences)
Last logged: 10 June 2022, 22:34:49

Challenge/Response error with SniTun server (0 bytes read on a total of 32 expected bytes)

Home Assistant Core 2022.6.4
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.1
