### ISSUE TITLE
Unpin dependencies?

### ISSUE THREAD

**Issue by balloob** [NabuCasa/snitun#26]
https://github.com/NabuCasa/snitun/blob/9ccc9360abd02472f91bb64caba7986507f7c0a7/setup.py#L36

To make it more compatible with consumers like Home Assistant, can we unpin the dependencies?

**Comment by pvizeli** [comment]
cryptography should stay like it is but others we can also add `>=` ?

**Comment by balloob** [comment]
Well, unpin can still be `>=`, as we might have a min requirements. Just got a warning locally because `attrs` and async_timeout are pinned and not the same as HA.
